import React from "react";

const TermsConditions = () => {
  return (
    <div className="bg-gray-100 min-h-screen flex flex-col items-center justify-center p-8">
      <div className="max-w-4xl w-full bg-white shadow-md rounded-lg px-8 py-6">
        {/* <h1 className="text-2xl font-bold text-center mb-6"></h1> */}

        <div className="prose prose-blue">
          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-1">
              osam Terms of use
            </h4>
            <p className="text-gray-800 text-sm">
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules there under as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
              <br />
              This document is published in accordance with the provisions of
              Rule 3 (1) of the Information Technology (Intermediaries
              guidelines) Rules, 2011 that require publishing the rules and
              regulations, privacy policy and Terms of Use for access or usage
              of domain name [www.osam.com] (“Website”), including the related
              mobile site and mobile application (hereinafter referred to as
              “Platform”)
              <br />
              Your use of the Platform and services and tools are governed by
              the following terms and conditions ("Terms of Use") as applicable
              to the Platform including the applicable policies which are
              incorporated herein by way of reference. If You transact on the
              Platform, You shall be subject to the policies that are applicable
              to the Platform for such transaction. By mere use of the Platform,
              You shall be contracting with Flipkart Internet Private Limited
              and these terms and conditions including the policies constitute
              Your binding obligations, with Flipkart.
              <br />
              For the purpose of these Terms of Use, wherever the context so
              requires "You" or "User" shall mean any natural or legal person
              who has agreed to become a buyer on the Platform by providing
              Registration Data while registering on the Platform as Registered
              User using the computer systems. Flipkart allows the User to surf
              the Platform or making purchases without registering on the
              Platform. The term "We", "Us", "Our" shall mean Flipkart Internet
              Private Limited.
            </p>
          </div>

          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-2">
              2. Terms & Conditions:
            </h4>
            <ul className="list-disc list-inside text-gray-800 text-sm">
              <li className="text-gray-800 text-sm">
                {" "}
                Flipkart Foundation is a Section 8 company registered under the
                Companies Act 2013.
              </li>
              <li>
                The amount received as donation will be donated to NGOs and
                similar charitable organizations working in the selected
                thematic areas. You can visit www.flipkartfoundation.org to know
                more about this.
              </li>
              <li>The contribution, once made, will not be refunded.</li>
              <li>
                No certificate under section 80G of the Income Tax Act, 1961
                will be issued.
              </li>
              <li>
                By proceeding to donate, you understand and confirm that this
                donation is not from any foreign source as defined under Foreign
                Contribution (Regulation) Act, 2010.
              </li>
              <li>
                Flipkart Foundation disclaims any and all liability and assumes
                no responsibility whatsoever for consequences resulting from any
                actions or inactions of the NGOs or charitable organizations.
              </li>
              <li>
                By proceeding to donate the money, you consent and expressly
                waive any and all claims, rights of action and/or remedies
                (under law or otherwise) that you may have against any of the
                Flipkart Group entities arising out of or in connection with the
                aforesaid transaction.
              </li>
              <li>
                The donation is being collected on behalf of the Flipkart
                Foundation and is disbursed to Flipkart Foundation. Flipkart
                Internet Pvt Ltd disclaims all liabilities and assumes no
                responsibility for consequences resulting from actions/
                inactions of the Flipkart Foundation.
              </li>
              <li>
                Flipkart Internet Pvt. Ltd may share your Personal Identifiable
                Information which may include your name, phone number, etc with
                Flipkart Foundation.
              </li>
            </ul>
          </div>

          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-3">
              3. Restrictions
            </h4>
            <p className="text-gray-800 text-sm">
              You are specifically restricted from all of the following:
            </p>
            <ul className="list-disc list-inside text-gray-800 text-sm">
              <li>publishing any website material in any other media;</li>
              <li>
                selling, sublicensing and/or otherwise commercializing any
                website material;
              </li>
              <li>publicly performing and/or showing any website material;</li>
              <li>
                using this website in any way that is or may be damaging to this
                website;
              </li>
            </ul>
          </div>

          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-4">
              4. Your Content
            </h4>
            <p className="text-gray-800 text-sm">
              In these terms and conditions, "Your Content" shall mean any
              audio, video, text, images or other material you choose to display
              on this website. By displaying Your Content, you grant us a
              non-exclusive, worldwide irrevocable, sub licensable license to
              use, reproduce, adapt, publish, translate and distribute it in any
              and all media.
            </p>
          </div>

          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-5">
              5. No warranties
            </h4>
            <p className="text-gray-800 text-sm">
              This website is provided "as is," with all faults, and we make no
              express or implied representations or warranties of any kind
              related to this website or the materials contained on this
              website.
            </p>
          </div>

          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-6">
              6. Limitation of liability
            </h4>
            <p className="text-gray-800 text-sm">
              In no event shall we be liable for any indirect, consequential or
              special liability arising out of or in any way related to your use
              of this website.
            </p>
          </div>

          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-7">
              7. Indemnification
            </h4>
            <p className="text-gray-800 text-sm">
              You hereby indemnify to the fullest extent us from and against any
              and all liabilities, costs, demands, causes of action, damages and
              expenses arising in any way related to your breach of any of the
              provisions of these terms.
            </p>
          </div>

          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-8">
              8. Severability
            </h4>
            <p className="text-gray-800 text-sm">
              If any provision of these terms is found to be invalid under any
              applicable law, such provisions shall be deleted without affecting
              the remaining provisions herein.
            </p>
          </div>

          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-9">
              9. Variation of Terms
            </h4>
            <p className="text-gray-800 text-sm">
              We are permitted to revise these terms at any time as we see fit,
              and by using this website you are expected to review these terms
              regularly.
            </p>
          </div>

          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-10">
              10. Entire Agreement
            </h4>
            <p className="text-gray-800 text-sm">
              These terms constitute the entire agreement between us in relation
              to your use of this website and supersede all prior agreements and
              understandings.
            </p>
          </div>

          <div className="mb-8">
            <h4 className="text-lg font-bold" id="section-11">
              11. Governing Law & Jurisdiction
            </h4>
            <p className="text-gray-800 text-sm">
              These terms will be governed by and construed in accordance with
              the laws of the jurisdiction, and you submit to the non-exclusive
              jurisdiction of the state and federal courts for the resolution of
              any disputes.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsConditions;
